### ISSUE TITLE
User Preferences Extension Not Working on Deployment to NetSuite

### ISSUE THREAD

**Issue by GarvitSolanki** [oracle/netsuite-commerce#1]
_**On requesting the service file, the service file URL is giving 404 in response!
I have deployed and activated the extension on the SandBox Account...
Kindly help to solve the issue as soon as possible**_

**File**: netSuite-commerce/samples/2020-2/Example-part3/Modules/UserPreferences/JavaScript/Example.UserPreferences.Model.js

**this.urlRoot = function urlRoot() {
            return Utils.getAbsoluteUrl(
                getExtensionAssetsPath(
                    "Modules/UserPreferences/SuiteScript2/Example.UserPreferences.Service.ss"
                ), true
            )
        }**

**Error**: Request {"url":"https://www.woundcareeshop.com/sca-dev-2020-2-0_ss2/extensions/ExampleVendor/Example/1.0.2/Modules/UserPreferences/SuiteScript2/Example.UserPreferences.Service.ss?c=3635909_SB1&n=2&_=1620221902844","type":"GET","isLocal":false,"global":true,"processData":true,"async":true,"contentType":"application/x-www-form-urlencoded; charset=UTF-8","accepts":{"*":"*/*","text":"text/plain","html":"text/html","xml":"application/xml, text/xml","json":"application/json, text/javascript","script":"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},"contents":{"xml":{},"html":{},"json":{},"script":{}},"responseFields":{"xml":"responseXML","text":"responseText","json":"responseJSON"},"converters":{"text html":true},"flatOptions":{"url":true,"context":true},"jsonp":"callback","cache":false,"dataType":"json","parse":true,"emulateHTTP":false,"emulateJSON":false,"dataTypes":["text","json"],"crossDomain":false,"hasContent":false}

**Comment by stevegoldberg** [comment]
I'm sorry, I'm having understanding what's happening. It looks like you've changed the name of the service file, but not changed the name in the call?

Also, I want to make sure that you've gone through the standard steps of setting up your account to support SS 2.0? Eg, enabled the feature and also deployed the SSP 2.0 application and linked it to your domain?

**Comment by GarvitSolanki** [comment]
> I'm sorry, I'm having understanding what's happening. It looks like you've changed the name of the service file, but not changed the name in the call?
> 
> Also, I want to make sure that you've gone through the standard steps of setting up your account to support SS 2.0? Eg, enabled the feature and also deployed the SSP 2.0 application and linked it to your domain?

I am sorry that was a mistake while creating the issue here... I used the same name of the service file in the call...

I tried deploying exactly the same code here on my sandbox account but this error was still there...

I am completely new to Netsuite and trying to deploy the UserPreference Extension on SCA version 2020.2.0 !

**Comment by stevegoldberg** [comment]
I understand this is frustrating but can you follow the steps I put in my last comment? Specifically:

> Also, I want to make sure that you've gone through the standard steps of setting up your account to support SS 2.0? Eg, enabled the feature and also deployed the SSP 2.0 application and linked it to your domain?

Can you also check that you have activated the extension and that the file appears in the correct place in the file cabinet, ie SuiteScripts > Deploy_Extensions > ExampleVendor > Example > 1.0.2 > Modules > UserPreferences > SuiteScript2 ?

**Comment by GarvitSolanki** [comment]
> I understand this is frustrating but can you follow the steps I put in my last comment? Specifically:
> 
> > Also, I want to make sure that you've gone through the standard steps of setting up your account to support SS 2.0? Eg, enabled the feature and also deployed the SSP 2.0 application and linked it to your domain?
> 
> Can you also check that you have activated the extension and that the file appears in the correct place in the file cabinet, ie SuiteScripts > Deploy_Extensions > ExampleVendor > Example > 1.0.2 > Modules > UserPreferences > SuiteScript2 ?


The service file is appearing exactly at the path you described and also I activated the Extension using Extension Manager...
I enabled the Suitesript features in Setup > Comapny > Enable Features > SuiteCloud > SuiteScript

Is there anything that I have to change in the manifest file except for the vendor, and other basic details?

Sorry, I didn't get what to do with SSP 2.0 application... It would be a great help if you can provide a link on how to do this SSP application task or if you could connect!

**Comment by GarvitSolanki** [comment]
The issue is solved... Thanks for your help @stevegoldberg  ...
SuiteScript 2.0 SSP applications must be explicitly made available on websites and domains; unlike
SuiteScript 1.0 SSP applications, they are not available by default.

Referred document: https://docs.oracle.com/cloud/latest/netsuitecs_gs/NSSSM/NSSSM.pdf
pg no.176
