### ISSUE TITLE
Insufficient permission error

### ISSUE THREAD

**Issue by dhairyakanthalia** [oracle/netsuite-commerce#2]
{"type":"error.SuiteScriptError","name":"INSUFFICIENT_PERMISSION","message":"Permission Violation: You need a higher permission for custom record type Custom lead to access this page. Please contact your account administrator."
I am getting this error even though i have given all the permissions. Can anyone please tell me about the procedure for giving the permission to the roles for implementing the extension.

**Comment by stevegoldberg** [comment]
Hi. You should only raise issues here if they are specific to one of the code samples included in the repository -- can you tell me which code sample you're getting this error with?

(If this is unrelated to one of the code samples, you can ask this question on our official support community, https://community.oracle.com/netsuite/, or, if you wish, one of the unofficial ones our customers and partners have made themselves.)

**Comment by dhairyakanthalia** [comment]
I have raised issue for below mentioned code sample . I am getting error when i try to send data using post request as mentioned in this code sample.

netsuite-commerce/samples/2020-2/Example-part4/Modules/UserPreferences/SuiteScript2/Example.UserPreferences.Model.js

**Comment by stevegoldberg** [comment]
Are you sure? Because this sample does not deal with a custom record called "Custom lead" so I don't know how you could have got that error using this code.

**Comment by dhairyakanthalia** [comment]
I have implemented the same code as in netsuite-commerce/samples/2020-2/Example-part4/Modules/UserPreferences/SuiteScript2/Example.UserPreferences.Model.js but i am getting same error that is insufficient permission error.Then i tried creating a custom record custom lead then also i am getting the same error

**Comment by stevegoldberg** [comment]
OK. Have you followed the setup instructions in the article: https://developers.suitecommerce.com/develop-your-first-extension.html#part-4-set-up-records-and-implement-the-createpost-action ?

- Are you using a permission list on the record type?
- Have you added the customer center to the list, with full level access to viewing and editing?

**Comment by dhairyakanthalia** [comment]
The issue is solved... Thanks for your help @stevegoldberg 
i tried giving the permission to the role for the custom record and it worked
thank you
